Id: BellSoft.LibericaJDK
Name: Liberica JDK 11
Version: 11.0.7.10
Publisher: BellSoft
Homepage: https://bell-sw.com
License: GPLv2 with exceptions
Description: |
    Liberica JDK is available on a variety of platforms. It is built from OpenJDK which BellSoft contributes to and is thoroughly tested.
    Liberica JDK is compatible with the Java SE standard as confirmed by the JCK provided under the license from OpenJDK. Support options are available from BellSoft.
Installers:
    - Arch: x64
      Url: https://download.bell-sw.com/java/11.0.7+10/bellsoft-jdk11.0.7+10-windows-amd64.msi
      InstallerType: Msi
      Sha256: E3D95735FB8569E573466894425485FFFF84DBC7662EDDE53E60DE27DC7A0F14
